export const UserReducerValidTypes = {
    LOG_CURRENT_USER_START: 'LOG_CURRENT_USER_START',
    LOG_CURRENT_USER_FAILED: 'LOG_CURRENT_USER_FAILED',
    LOG_CURRENT_USER_SUCCESS: 'lOG_CURRENT_USER_SUCCESS',

}