export const UserReducerValidTypes = {
    LOGIN_CURRENT_USER_START: 'LOGIN_CURRENT_USER_START',
    LOGIN_CURRENT_USER_FAILED: 'LOGIN_CURRENT_USER_FAILED',
    LOGIN_CURRENT_USER_SUCCESS: 'lOGIN_CURRENT_USER_SUCCESS',
    LOGOUT_CURRENT_USER_START: 'LOGOUT_CURRENT_USER_START',
    LOGOUT_CURRENT_USER_FAILED: 'LOGOUT_CURRENT_USER_FAILED',
    LOGOUT_CURRENT_USER_SUCCESS: 'lOGOUT_CURRENT_USER_SUCCESS',

}